title: <p align="center"> Jeyashree Murugappan </p>
logo: /assets/img/logo1.png

description:
  <p align="center">
  <a href="https://github.com/JeyashreeMurugappan">GitHub</a>
  
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  <br>
  </p>
theme: jekyll-theme-minimal